# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArcheryNotes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ArcheryNotes
  pod 'Fabric'
  pod 'Crashlytics'

  target 'ArcheryNotes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNI18n', :path => '../node_modules/react-native-i18n'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'ArcheryNotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ArcheryNotes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ArcheryNotes-tvOS

end
