# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "b333237f-aa05-42fd-8ac2-4a6c881772db"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "08fbdc13d58c69ad18c5e09f9ed86d06d11b258d",
    build_secret: "7169297860bdaf1b6b8f6120c13baddcb31e3260d44d09dfe1bb8d2b58a0205c"
  )
end
